# 项目相关配置
yk:
  # 名称
  name: YK
  # 版本
  version: 3.0.0
  # 年份
  copyrightYear: 2020
  # 演示demo开关
  demoEnabled: true
  # 文件路径
  profile:
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    # tomcat最大线程数 默认200
    max-threads: 800
    # tomcat启动初始化线程数, 默认25
    min-spare-threads: 30

# Spring配置
spring:
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 设置总上传的文件大小
      max-request-size: 2500MB
#  # 服务
#  devtools:
#    restart:
#      # 热部署开关
#      enabled: true

# MyBatis配置
mybatis:
  type-aliases-package: com.yk
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unAuth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: 1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 文件上传配置
file:
  # 本地文件上传位置(正式环境 /yk/upload/)
  localFilePath: E:/ykUpload/
  # fastDFS文件服务根地址
  fastDFSAddr: http://www.yukaifan.top:8080/

# fastDFS配置
fastdfs:
  # 最大连接数 并发量较大的话可加大连接数
  maxStorageConnection: 8
  # 连接超时时间(默认10秒)
  connectTimeout: 1000
  networkTimeout: 3000
  charset: UTF-8
  # 是否开始防盗链
  httpAntiStealToken: false
  # 防盗秘钥(服务端与客户端必须一致)
  httpSecretKey: 13a1d2ead6a24a6747dbd0f7462adf86
  httpTrackerHttpPort: 80
  # tracker访问地址
  trackerServers: www.yukaifan.top:22122

# 阿里云配置
aliyun:
  oss:
    accessKeyId: LTAIoc5iy7rzY5oF
    accessKeySecret: B7INLs3bwisLsUjcAcwNWx0RU4zCKI
    endpoint: oss-cn-qingdao.aliyuncs.com
    bucketName: yk-platform
